<?php

namespace Ctg\MainBundle\Repository;

/**
 * DemandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllCategorie(){
      $query = $this->_em->createQuery('SELECT * FROM CtgMainBundle:Demandes');
      $results = $query->getResult();
      return $results;
    }
}
