<?php

namespace Ctg\MainBundle\Repository;

/**
 * UtilisateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateursRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUtilisateurGestionnaire(){
      $query = $this->_em->createQuery("SELECT * FROM CtgMainBundle:Utilisateurs");
      $results = $query->getResult();
      return $results;
    }
}
